version: "3.7"

services:
  application:
    container_name: clock_degrees
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c "npx prisma migrate dev && npm run start"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - "./:/app"
    networks:
      - clock_degrees_network
      - postgres
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./private/var/lib/postgresql:/var/lib/postgresql
    networks:
      - postgres

networks:
  clock_degrees_network:
    name: clock_degrees_network
    driver: bridge
  postgres:
    name: postgres
    driver: bridge
